config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', registrations: 'registrations' }

  root 'questions#index'

  get '/search', to: 'search#index'

  concern :commentable do
    resources :comments, shallow: true, only: [:create]
  end

  resources :questions, except: [:edit] do
    concerns :commentable

    resources :answers, shallow: true, except: [:index, :show, :new] do
      post :mark_as_best, on: :member
      post :like, on: :member
      post :unlike, on: :member

      concerns :commentable
    end

    resources :subscriptions, only: [:create, :destroy]

    post :like, on: :member
    post :unlike, on: :member
  end

  resources :rewards, only: [:index]
  resources :attachments, only: [:destroy]
  resources :links, only: [:destroy]

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        resources :answers, shallow: true, only: [:index, :show, :create, :update, :destroy]
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  searchkick

  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one :reward, dependent: :destroy

  belongs_to :author,
             class_name: 'User',
             foreign_key: 'user_id'

  belongs_to :best_answer,
             class_name: 'Answer',
             foreign_key: 'best_answer_id',
             optional: true

  has_many_attached :files, dependent: :destroy

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank, allow_destroy: true

  validates :title, :body, :author, presence: true

  scope :daily, -> { where('created_at > ? ', Time.now - 1.day) }

  after_create :calculate_reputation
  after_create :subscribe_author

  def search_data
    attrs = attributes.dup
    relational = {
      author_email: author.email,
    }
    attrs.merge! relational
  end

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end

  def subscribe_author
    Subscription.create(question_id: self.id, user_id: self.author.id)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  skip_before_action :verify_authenticity_token
  before_action -> { authorize! :create, Question }, only: [:index, :show, :create]
  before_action :find_question, only: [:show, :update, :destroy]

  def index
    @questions = Question.all
    render json: @questions, each_serializer: QuestionsSerializer
  end

  def show
    render json: @question, serializer: QuestionSerializer
  end

  def create
    question = current_resource_owner.questions.new(question_params)

    if question.save
      render json: question, serializer: QuestionSerializer, status: :created
    else
      render json: { errors: question.errors }, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, @question
    if @question.update(question_params)
      render json: @question, serializer: QuestionSerializer, status: :created
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, @question
    if @question.destroy
      render json: { status: :ok }
    else
      render json: { errors: "Something went wrong. Question did not delete." }, status: :unprocessable_entity
    end
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :update, :destroy]
  after_action :publish_question, only: [:create]

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.build
    @answer.links.build
    @best_answer = @question.best_answer
    @answers = @question.answers.where.not(id: @question.best_answer_id)
    @question.links.build
    @question_comment = @question.comments.build
    @answer_comment = @answer.comments.build

    if current_user
      @subscription = Subscription.find_by(question_id: @question.id, user_id: current_user.id)
    end

    gon.question_id = @question.id
    gon.answer_comment = @answer_comment
  end

  def new
    @question = Question.new
    @question.links.build
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    if @question.user_id == current_user.id
      @question.destroy
      redirect_to questions_path, notice: 'Question successfully deleted.'
    else
      flash[:notice] = "You can't delete someone else's question."
      render :show
    end
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast(
      'questions_channel',
      ApplicationController.render(
        partial: 'questions/question',
        locals: { question: @question }
      )
    )
  end

  def question_params
    params.require(:question).permit(:title,
                                     :body,
                                     files: [],
                                     links_attributes: [:id, :name, :url, :_destroy],
                                     reward_attributes: [:title, :image])
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question, local: true do |form|
  .question
    p
      = form.label :title
      br
      = form.text_field :title

    p
      = form.label :body
      br
      = form.text_area :body, id: :question_body, rows: 7, cols: 60

    p
      = form.label :files
      br
      = form.file_field :files, multiple: true, direct_upload: true

  p#links Links:
  = form.fields_for :links do |l|
    = render 'link_fields', f: l

  = link_to_add_association 'add link', form, :links, \
                                        'data-association-insertion-node' => '.nested-fields', \
                                        'data-association-insertion-method' => 'after'

  .reward
    p Reward:
    = form.fields_for :reward_attributes do |r|
      = r.label :title
      = r.text_field :title
      = r.label :image
      = r.file_field :image, multiple: false, direct_upload: true

  p = form.submit 'Ask'

p = link_to 'Back', questions_path

app/views/questions/_question.html.slim
div = link_to question.title, question_path(question)

app/views/questions/_question_show.html.slim
div id="question-#{@question.id}" class="question"
  h1 = @question.title
  p = @question.body

  .question-votes
    b Rating:
    => link_to 'like', like_question_path(@question), \
                       class: 'question-like', \
                       method: :post, \
                       data: { type: :json }, \
                       remote: true \
                       if can?(:like, @question)

    b class="question-rating" data-question-rating="#{@question.rating}" => @question.rating

    = link_to 'unlike', unlike_question_path(@question), \
                        class: 'question-unlike', \
                        method: :post, \
                        data: { type: :json }, \
                        remote: true \
                        if can?(:unlike, @question)

  .files
    - if @question.files.attached?
      - @question.files.each do |file|
        = content_tag :div, id: "question-file-#{file.id}"
          p = link_to file.filename.to_s, url_for(file)
          - if can?(:destroy, @question)
            = link_to 'Delete',  attachment_path(file, question_id: @question.id), method: :delete, local: false

  .links
    p Links:
    = render 'shared/links', resource: @question, question_id: @question.id

  .actions
    - if can?(:update, @question)
      p = link_to 'Edit', '#', class: 'edit-question-link'

      .question-errors
        = render 'shared/errors', resource: @question

      = form_with model: @question, class: 'hidden', html: { id: 'edit-question-form' }, local: false do |form|
        = form.label :title
        = form.text_field :title
        = form.label :body
        = form.text_area :body, id: :question_body, rows: 7, cols: 60
        = form.label :files
        = form.file_field :files, multiple: true, direct_upload: true

        p#links Links:
        = form.fields_for :links do |l|
          = render 'link_fields', f: l
        = link_to_add_association 'add link', form, :links, \
                                              'data-association-insertion-node' => '.nested-fields', \
                                              'data-association-insertion-method' => 'after'
        = form.submit 'Update'

    - if can?(:destroy, @question)
      = link_to 'Delete', @question, local: true, method: :delete, data: { confirm: 'Are you sure?' }

    - if @subscription.present?
      - if can?(:destroy, @subscription)
        = link_to 'Unsubscribe', question_subscription_path(@question, @subscription), method: :delete
    - else
      - if can?(:create, Subscription)
        = link_to 'Subscribe', question_subscriptions_path(@question), method: :post

  h2 Question Comments
  .comments
    = render @question.comments

  .new-question-comment
    - if can?(:create, @question_comment)
      = render 'comments/form', commentable: @question, comment: @question_comment

app/views/questions/_question_simple.html.slim
div id="question-#{@question.id}" class="question"
  h1 = @question.title
  p = @question.body

  .question-votes
    b Rating:
    => link_to 'like', like_question_path(@question), \
                       class: 'question-like', \
                       method: :post, \
                       data: { type: :json }, \
                       remote: true \
                       if can?(:like, @question)

    b class="question-rating" data-question-rating="#{@question.rating}" => @question.rating

    = link_to 'unlike', unlike_question_path(@question), \
                        class: 'question-unlike', \
                        method: :post, \
                        data: { type: :json }, \
                        remote: true \
                        if can?(:unlike, @question)

  .files
    - if @question.files.attached?
      - @question.files.each do |file|
        = content_tag :div, id: "question-file-#{file.id}"
          p = link_to file.filename.to_s, url_for(file)
          - if user_signed_in? && @question.author == current_user
            = link_to 'Delete',  attachment_path(file, question_id: @question.id), method: :delete, local: false

  .links
    p Links:
    = render 'shared/links', resource: @question, question_id: @question.id

  .actions
    - if can?(:update, @question)
      p = link_to 'Edit', '#', class: 'edit-question-link'

      .question-errors
        = render 'shared/errors', resource: @question

      = form_with model: @question, class: 'hidden', html: { id: 'edit-question-form' }, local: false do |form|
        = form.label :title
        = form.text_field :title
        = form.label :body
        = form.text_area :body, id: :question_body, rows: 7, cols: 60
        = form.label :files
        = form.file_field :files, multiple: true, direct_upload: true

        p#links Links:
        = form.fields_for :links do |l|
          = render 'link_fields', f: l
        = link_to_add_association 'add link', form, :links, \
                                              'data-association-insertion-node' => '.nested-fields', \
                                              'data-association-insertion-method' => 'after'
        = form.submit 'Update'

    - if can?(:destroy, @question)
      = link_to 'Delete', @question, local: true, method: :delete, data: { confirm: 'Are you sure?' }

app/views/questions/index.html.slim
h1 Все вопросы

- if can?(:create, Question)
  = link_to 'Ask Question', new_question_path

br
br
- cache collection_cache_key_for :question do
  .questions
    = render @questions

app/views/questions/like.js.erb
$('.question-rating').html("<%= @question.rating %>")

app/views/questions/new.html.slim
h1 New Question

= render 'form'

app/views/questions/show.html.slim
- cache @question do
  = render partial: "question_show", object: @question

  h2 Answers
  ol.answers
    - if @question.best_answer != nil
      = render 'answers/best_answer', resource: @best_answer
    = render @answers

  .answer-errors
    = render 'shared/errors', resource: @answer

  = form_with model: [@question, @answer], class: 'new-answer', local: false do |form|
    = form.label :body
    = form.text_area :body, id: :answer_body, name: 'answer[body]', rows: 7, cols: 60
    = form.label :files
    = form.file_field :files, multiple: true, direct_upload: true

    p#links Links:
    = form.fields_for :links do |l|
      = render 'link_fields', f: l

    = link_to_add_association 'add link', form, :links, \
                                          'data-association-insertion-node' => '.nested-fields', \
                                          'data-association-insertion-method' => 'after'

    = form.submit 'Add Answer'

  p = link_to 'Back to Questions', questions_path

app/views/questions/unlike.js.erb
$('.question-rating').html("<%= @question.rating %>")

app/views/questions/update.js.erb
$('.question-errors').html("<%= render 'shared/errors', resource: @question %>")

<% if !@question.errors.present? %>
  $('.question').html('<%= j render partial: "question_simple", object: @question %>')
<% end %>