config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', registrations: 'registrations' }

  root 'questions#index'

  get '/search', to: 'search#index'

  concern :commentable do
    resources :comments, shallow: true, only: [:create]
  end

  resources :questions, except: [:edit] do
    concerns :commentable

    resources :answers, shallow: true, except: [:index, :show, :new] do
      post :mark_as_best, on: :member
      post :like, on: :member
      post :unlike, on: :member

      concerns :commentable
    end

    resources :subscriptions, only: [:create, :destroy]

    post :like, on: :member
    post :unlike, on: :member
  end

  resources :rewards, only: [:index]
  resources :attachments, only: [:destroy]
  resources :links, only: [:destroy]

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        resources :answers, shallow: true, only: [:index, :show, :create, :update, :destroy]
      end
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    authorize! :read, :all
    @query = params[:q]
    @model = params[:model]

    if @model == 'Everywhere'
      @response = {}
      @response['questions'] = Question.search(@query)
      @response['answers'] = Answer.search(@query)
      @response['users'] = User.search(@query)
      @response['comments'] = Comment.search(@query)
    else
      @response = @model.singularize.constantize.search(@query)
    end
  end
end

app/views/search/_answer.html.slim
=> resource.body
br
= link_to resource.question.title, question_path(resource.question)

app/views/search/_comment.html.slim
= resource.body
br
- if resource.commentable.class == Answer
  = link_to resource.commentable.question.title, question_path(resource.commentable.question)
- else
  = link_to resource.commentable.title, question_path(resource.commentable)

app/views/search/_question.html.slim
= link_to resource.title, question_path(resource)

app/views/search/_user.html.slim
= resource.email

app/views/search/index.html.slim
h1 = "Search results for: #{@query}"

-if @response.is_a?(Hash)
  - @response.each do |key, value|
    h3 = "#{key.capitalize}:"
    -if @response[key].present?
      - @response[key].each do |res|
        p = render "#{key.singularize}", resource: res
    - else
      p = "No #{key} searched for this query..."

- else
  h3 = "#{@model}"
  -if @response.present?
    - @response.each do |res|
      -if res.is_a?(@model.singularize.constantize)
          p = render "#{@model.singularize.downcase}", resource: res
  - else
    p No results for this search...

p = link_to 'Back to Questions', questions_path