config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', registrations: 'registrations' }

  root 'questions#index'

  get '/search', to: 'search#index'

  concern :commentable do
    resources :comments, shallow: true, only: [:create]
  end

  resources :questions, except: [:edit] do
    concerns :commentable

    resources :answers, shallow: true, except: [:index, :show, :new] do
      post :mark_as_best, on: :member
      post :like, on: :member
      post :unlike, on: :member

      concerns :commentable
    end

    resources :subscriptions, only: [:create, :destroy]

    post :like, on: :member
    post :unlike, on: :member
  end

  resources :rewards, only: [:index]
  resources :attachments, only: [:destroy]
  resources :links, only: [:destroy]

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        resources :answers, shallow: true, only: [:index, :show, :create, :update, :destroy]
      end
    end
  end
end

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b = "#{resource.errors.count} error(s) detected:"
  ul
    -resource.errors.full_messages.each do |message|
      li = message

app/views/shared/_flash.html.slim
- flash.each do |key, message|
  = content_tag :p, message

app/views/shared/_links.html.slim
- resource.links.each do |link|
  - if link.persisted?
    = link_to link.name,
              link.url,
              class: "#{'gist-link' if link.gist?}",
              data: { link_id: link.id }
    - if can?(:destroy, resource)
      = link_to 'Delete',  link_path(link, question_id: question_id), method: :delete, local: false

    - if link.gist?
      div class="gist-content hidden" data-link-id="#{link.id}"

app/views/shared/_nav.html.slim
- if user_signed_in?
  = button_to "Log Out", destroy_user_session_path, method: :delete
  = link_to "My Rewards", rewards_path
- else
  = button_to "Sign Up", new_user_registration_path, method: :get
  = button_to "Log In", new_user_session_path, method: :get

app/views/shared/_search.html.slim
.search
  = form_with url: '/search', method: :get, local: true do |f|
    => f.label :q, "Search for:"
    => f.text_field :q
    => f.select :model, ['Everywhere', 'Questions', 'Answers', 'Users', 'Comments']
    = f.submit 'Search'