config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', registrations: 'registrations' }

  root 'questions#index'

  get '/search', to: 'search#index'

  concern :commentable do
    resources :comments, shallow: true, only: [:create]
  end

  resources :questions, except: [:edit] do
    concerns :commentable

    resources :answers, shallow: true, except: [:index, :show, :new] do
      post :mark_as_best, on: :member
      post :like, on: :member
      post :unlike, on: :member

      concerns :commentable
    end

    resources :subscriptions, only: [:create, :destroy]

    post :like, on: :member
    post :unlike, on: :member
  end

  resources :rewards, only: [:index]
  resources :attachments, only: [:destroy]
  resources :links, only: [:destroy]

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        resources :answers, shallow: true, only: [:index, :show, :create, :update, :destroy]
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  searchkick

  has_many :links, dependent: :destroy, as: :linkable
  belongs_to :question, touch: true
  belongs_to :author,
             class_name: 'User',
             foreign_key: 'user_id'

  has_many_attached :files, dependent: :destroy

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :author, presence: true
  validates :body, presence: true,
                   uniqueness: { scope: :question_id, case_sensitive: false }

  after_create :send_notification

  def search_data
    attrs = attributes.dup
    relational = {
      author_email: author.email,
    }
    attrs.merge! relational
  end

  private

  def send_notification
    NewAnswerNotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :find_question, only: [:create, :edit]
  before_action :load_answer, only: [:edit, :update, :destroy, :mark_as_best]
  after_action :publish_answer, only: [:create]

  authorize_resource

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user_id = current_user.id

    @answer.save
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    @answer.destroy
  end

  def mark_as_best
    question = @answer.question
    question.update(best_answer_id: @answer.id)
    question.reward.update(user_id: @answer.user_id) if question.reward.present?

    redirect_to question
  end

  private

  def publish_answer
    return if @answer.errors.any?

    html = ApplicationController.render(
      partial: 'answers/answer_simple',
      locals: { answer: @answer }
    )

    ActionCable.server.broadcast("question_#{@answer.question.id}", { html: html, author_id: @answer.user_id })
  end

  def load_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def find_question
    @question = Question.with_attached_files.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:id, :name, :url, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  skip_authorization_check
  before_action :find_answer, only: [:show, :update, :destroy]


  def index
    @question = Question.find(params[:question_id])
    render json: @question.answers, each_serializer: AnswersSerializer
  end

  def show
    render json: @answer, serializer: AnswerSerializer
  end

  def create
    @question = Question.find(params[:question_id])
    answer = @question.answers.new(answer_params)
    answer.author = current_resource_owner

    if answer.save
      render json: answer, status: :created, serializer: AnswerSerializer
    else
      render json: { errors: answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, @answer
    if @answer.update(answer_params)
      render json: @answer, status: :created
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, @answer
    if @answer.destroy
      render json: { status: :ok }
    else
      render json: { errors: "Something went wrong. Answer did not delete." }, status: :unprocessable_entity
    end
  end

  private

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  = content_tag :li, id: "answer-#{answer.id}", class: "card"

    => answer.body

    .answer-votes
      b> Rating:
      => link_to 'like', like_answer_path(answer), \
                         class: 'answer-like', \
                         method: :post, \
                         data: { answer_id: answer.id, type: :json }, \
                         remote: true \
                         if can?(:like, answer)

      b class="answer-#{answer.id}-rating" => answer.rating

      = link_to 'unlike', unlike_answer_path(answer), \
                          class: 'answer-unlike', \
                          method: :post, \
                          data: { answer_id: answer.id, type: :json }, \
                          remote: true \
                          if can?(:unlike, answer)

    .actions
      - if can?(:mark_as_best, answer)
        => link_to 'Mark as Best', mark_as_best_answer_path(answer), method: :post, local: false

      - if can?(:update, answer)
        => link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
      - if can?(:destroy, answer)
        = link_to 'Delete', answer, method: :delete, remote: true

      =content_tag :div, class: "answer-edit-errors-#{answer.id}"
        = render 'shared/errors', resource: answer

      = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" }, local: false do |f|
        = f.label :body
        = f.text_area :body, name: 'answer[body]', rows: 7, cols: 60
        = f.label :files
        = f.file_field :files, multiple: true, direct_upload: true
        p#links Links:
        = f.fields_for :links do |l|
          = render 'link_fields', f: l
        = link_to_add_association 'add link', f, :links, \
                                              'data-association-insertion-node' => '.nested-fields', \
                                              'data-association-insertion-method' => 'after'
        = f.submit 'Save'

    br
    b Answer Comments
    .comments
      = render answer.comments

    div class="new-answer-#{answer.id}-comment"
      - if can?(:create, @answer_comment)
        = render 'comments/form', commentable: answer, comment: @answer_comment

    .links
      p Links:
      = render 'shared/links', resource: answer, question_id: answer.question.id

    .answer-files
      - if answer.files.attached?
        - answer.files.each do |file|
          p = link_to file.filename.to_s, url_for(file)
          - if can?(:destroy, answer)
            = link_to 'Delete', attachment_path(file, question_id: answer.question.id), method: :delete, local: false

app/views/answers/_answer_simple.html.slim
= content_tag :li, id: "answer-#{answer.id}", class: "card"

  => answer.body

  .answer-votes
    b> Rating:
    b class="answer-#{answer.id}-rating" => answer.rating

  .links
    p Links:
    - answer.links.each do |link|
      - if link.persisted?
        = link_to link.name,
                  link.url,
                  data: { link_id: link.id }

  .answer-files
    - if answer.files.attached?
      - answer.files.each do |file|
        p = link_to file.filename.to_s, url_for(file)

app/views/answers/_best_answer.html.slim
- cache @best_answer do
  = content_tag :li, id: "answer-#{@best_answer.id}", style: 'border: 1px solid #000; padding: 10px;'
    b => "[Best]"

    => @best_answer.body

    .answer-votes
      b Rating:
      => link_to 'like', like_answer_path(@best_answer), \
                         class: 'answer-like', \
                         method: :post, \
                         data: { answer_id: @best_answer.id, type: :json }, \
                         remote: true \
                         if can?(:like, @best_answer)

      b class="answer-#{@best_answer.id}-rating" => @best_answer.rating

      = link_to 'unlike', unlike_answer_path(@best_answer), \
                          class: 'answer-unlike', \
                          method: :post, \
                          data: { answer_id: @best_answer.id, type: :json }, \
                          remote: true \
                          if can?(:unlike, @best_answer)

    - if @best_answer.question.reward.present?
      .reward
        = image_tag url_for(@best_answer.question.reward.image)
        = @best_answer.question.reward.title

    - if can?(:update, Answer)
      => link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: @best_answer.id }
    - if can?(:destroy, Answer)
      = link_to 'Delete', @best_answer, method: :delete, remote: true

    .links
      p Links:
      = render 'shared/links', resource: @best_answer, question_id: @best_answer.question.id

    .answer-files
      - if @best_answer.files.attached?
        - @best_answer.files.each do |file|
          p = link_to file.filename.to_s, url_for(file)
          - if can?(:destroy, @best_answer)
            = link_to 'Delete', attachment_path(file, question_id: @best_answer.question.id), method: :delete, local: false

      =content_tag :div, class: "answer-edit-errors-#{@best_answer.id}"
        = render 'shared/errors', resource: @best_answer

      = form_with model: @best_answer, class: 'hidden', html: { id: "edit-answer-#{@best_answer.id}" }, local: false do |f|
        = f.label :body
        = f.text_area :body, name: 'answer[body]', rows: 7, cols: 60
        = f.label :files
        = f.file_field :files, multiple: true, direct_upload: true
        = f.submit 'Save'

app/views/answers/_link_fields.html.slim
.nested-fields
  p
    = f.label :name, 'Link name'
    = f.text_field :name
  p
    = f.label :url
    = f.text_field :url

  = link_to_remove_association "remove link", f

app/views/answers/create.js.erb
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>")

<% if @answer.persisted? %>
  $('.answers').append("<%= j render 'answer_simple', answer: @answer %>")
  $('.new-answer #answer_body').val('')
<% end %>

app/views/answers/destroy.js.erb
$('#answer-<%= @answer.id %>').remove();

app/views/answers/mark_as_best.js.erb
$('.answers').html('<%= j render @question.answers %>')

app/views/answers/update.js.erb
$('.answer-edit-errors-' + '<%= @answer.id %>').html("<%= render 'shared/errors', resource: @answer %>")

<% if !@answer.errors.present? %>
  $('#answer-' + "<%= @answer.id %>").replaceWith("<%= j render 'answer_simple', answer: @answer %>")
<% end %>